### ISSUE TITLE
Multipart Upload Error

### ISSUE THREAD

**Issue by vikash159** [bfwg/springboot-jwt-starter#11]
unable to upload file. can you add multipart uploading using rest apis.
using multipart/form-data from postman i got error like
Could not parse multipart servlet request; nested exception is java.io.IOException: org.apache.tomcat.util.http.fileupload.FileUploadException: the request was rejected because no multipart boundary was found

**Comment by bfwg** [comment]
Hey @vikash159 , upload files is not a part of the purpose of this starter project. 
However, the below code block should do the trick for you.
```java
@RequestMapping ( method = RequestMethod.POST, value = "/upload", consumes = "multipart/form-data" , produces = { "application/json", "application/xml" } )
    public ResponseEntity uploadFile( @RequestParam( value = "file" ) MultipartFile file ) {

    // do something with the file...
    // return ResponseEntity.ok() if file is valid.
    // return ResponseEntity.badRequest() if file is bad.

}
```

**Comment by bfwg** [comment]
Hey, @vikash159 have I answered your question? If so, can I close this now?

**Comment by vikash159** [comment]
Thanks that works
