### ISSUE TITLE
access login end point from angular with CORS activated

### ISSUE THREAD

**Issue by xpoveda** [bfwg/springboot-jwt-starter#22]
Hi, 

When I launch this http request with postman, the api rest works perfect.

http://localhost:8080/auth/login
POST 
json application
{"username":"user","password":"123"}

But when I try the same action from angular application returns 404 error.

I have study to have the api rest in http://localhost:8080 and the frontend in http://localhost:4200 and this makes a problem with CORS (cross origin) when the call is from a browser.

You have solved this in angular starter jwt kit with uses a proxy, but this is a solution for dev mode, but not for production mode.

The api rest (spring boot source code) should have CORS enabled.

I have make this in AuthenticationController.java:
```
  @CrossOrigin(origins = "http://localhost:4200")
    @RequestMapping(value = "/login", method = RequestMethod.POST)
```

And in angular.component.ts

```

import { Component, OnInit } from '@angular/core';
import { HttpClient, HttpHeaders } from "@angular/common/http";

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements OnInit {
  title = 'app';
  results = '';
  constructor(private http: HttpClient){
  }
  ngOnInit(): void {

    let body       = {"username":"user","password":"123"};
    //let options    = { headers: new HttpHeaders({ 'Content-Type': 'application/json' }) };

    this.http.post('http:/localhost:8080/auth/login', body)
      .subscribe(data => {
      console.log(data);
      }
    );
  }
}
```

But not works, can you help me?

Thanks so much!!

Xavier.

**Comment by bfwg** [comment]
Hi @xpoveda 
>You have solved this in angular starter jwt kit with uses a proxy, but this is a solution for dev mode, but not for production mode.

For production, usually you build your frontend Angular project into static files and serve them on port :8080 instead of running a dev server(:4200) to serve them.

Please open a new issue in https://github.com/bfwg/angular-spring-starter project if you more questions. 

Thanks!
