### ISSUE TITLE
How to revoke token when user logout ?

### ISSUE THREAD

**Issue by vikrampaygude** [bfwg/springboot-jwt-starter#24]

**Comment by bfwg** [comment]
Hi @vikrampaygude , do you want to revoke one specific token or do you want to revoke ALL token for a user when they log out?

**Comment by vikrampaygude** [comment]
Hi,  I want revoke all the tokens of user on logout.

**Comment by bfwg** [comment]
Then you want to set https://github.com/bfwg/springboot-jwt-starter/blob/master/src/main/java/com/bfwg/model/User.java#L143 to now on logout
