### ISSUE TITLE
what to do for AnonAuthentication class?

### ISSUE THREAD

**Issue by softboy99** [bfwg/springboot-jwt-starter#3]
There is a class "TokenBasedAuthentication" extends AbstractAuthenticationToken, "AnonAuthentication" also extends AbstractAuthenticationToken. what difference of the two? why need 2 class extends AbstractAuthenticationToken? Is it for Anonymous?

**Comment by bfwg** [comment]
That's correct, AnonAuthentication is for Anonymous users. By default if the user is not authenticated, we treat them as an anonymous user. TokenBasedAuthentication is for authenticated users.
