### ISSUE TITLE
Authorization header is not checked after user login

### ISSUE THREAD

**Issue by zhengye1** [bfwg/springboot-jwt-starter#5]
I use postman to test backend part right now. If I didn't authenticate, it return 403, which is correct. But once I submit the post request with login username and password, return back the token, then I call /whoami, it will still return response to me without verify the header contains the jwt token or not.

In my understanding, for every request that need privilege, like trying to get the response from /whoami, it need to authenticate first, get the jwt token, and then verify the token in the header?

**Comment by bfwg** [comment]
@zhengye1 what result are you getting after calling `/whoami`? How are you setting the `Authentication` header?

**Comment by zhengye1** [comment]
It seems like postman contains the auth-token as you described above.

I using SOAP UI to test again, and it works.
