### ISSUE TITLE
can i  add jackson dependency as it is not compiling

### ISSUE THREAD

**Issue by sarfarazengglb** [bfwg/springboot-jwt-starter#6]
can i  add jackson dependency as it is not compiling

**Comment by bfwg** [comment]
@sarfarazengglb Can you give me more detail of the issue?

**Comment by sarfarazengglb** [comment]
What is pr?

**Comment by bfwg** [comment]
@sarfarazengglb hey, a PR is a Pull Request. More information on Pull requests **https://yangsu.github.io/pull-request-tutorial/**

**Comment by sarfarazengglb** [comment]
It was direct download.
![error](https://cloud.githubusercontent.com/assets/6543585/26282653/7a128cc6-3e26-11e7-9be5-2c5ab0f13a3b.PNG)

It works after inserting the below dependencies
![jacksonjars](https://cloud.githubusercontent.com/assets/6543585/26282672/f2f9efd0-3e26-11e7-9685-9eefef5627e7.PNG)
![sucess](https://cloud.githubusercontent.com/assets/6543585/26282678/0f0d7336-3e27-11e7-9c4d-13d5ac7666da.PNG)

**Comment by sarfarazengglb** [comment]
It seems issue with my local Repo. However you can simulate the case by directly downloading the zip and setting it up.You can close the Issue if it works at your end.

**Comment by bfwg** [comment]
@sarfarazengglb Can you try with inserting those two dependencies?
```
		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-databind</artifactId>
		</dependency>
		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-annotations</artifactId>
		</dependency>
```
If that fixes your issue, I'll create a pull request for this.
